- name: OS family
  fail:
    msg: "OS family is not a `Debian'."
  when: ansible_os_family != "Debian"

- name: avoid package conflicts
  script: "packages_should_not_exist.sh {{ item }}"
  with_items:
    - "{{ kelleyk_emacs_old_package }}"

- name: emacs stable releases repository
  become: yes
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "{{ kelleyk_emacs_repository }}"

- name: emacs packages
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - "{{ kelleyk_emacs_main_package }}"
    - "{{ kelleyk_emacs_optional_package | default([], true) }}"

# Local Variables:
# indent-tabs-mode: nil
# End:
